Cloud-Officer/ci-actions

linters/flake8/README.md, linters/flake8/action.yml
Add docstrings check support for flake8.
=> Add docstrings support to flake8 linter.

.github/workflows/build.yml, aws/action.yml, codedeploy/checkout/action.yml, jira/action.yml, licenses/action.yml, linters/actionlint/action.yml, linters/bandit/action.yml, linters/codeql/README.md, linters/codeql/action.yml, linters/eslint/action.yml, linters/flake8/action.yml, linters/golangci/action.yml, linters/hadolint/action.yml, linters/ktlint/action.yml, linters/markdownlint/action.yml, linters/phpcs/action.yml, linters/phpstan/action.yml, linters/pmd/action.yml, linters/protolint/action.yml, linters/rubocop/action.yml, linters/shellcheck/action.yml, linters/swiftlint/action.yml, linters/yamllint/action.yml, setup/README.md, setup/action.yml, soup/action.yml, variables/action.yml, variables/variables.sh
Bumped all actions to latest and added rabbitmq and elasticsearch.
=> Bumped all actions to latest and added rabbitmq and elasticsearch

soup/action.yml
Second method to disable homebrew updates.
=> Second method to disable homebrew updates

linters/eslint/action.yml
Version pin eslint at 8.57.0.
Version 9.0.0 was released yesterday and is not backward compatible (new command-line syntax and arguments).
We will eventually need to upgrade, but this will mean rewriting the `.eslintrc` file in all repositories, as well a modifying the `build.yaml` actions to use the new command-line arguments in all repositories as well.
This is a work-around/transitional solution to restore the eslint functionnality in the meantime.
```
v9.0.0
eslint version:v9.0.0
Running eslint with reviewdog 🐶 ...
Invalid option '--ext' - perhaps you meant '-c'?
You're using eslint.config.js, some command line flags are no longer available. Please see https://eslint.org/docs/latest/use/command-line-interface for details.
reviewdog: parse error: failed to unmarshal rdjson …
```
=> Version pin eslint at 8.57.0

linters/phpstan/action.yml, setup/action.yml
Upgraded to webfactory/ssh-agent@v0.9.0 to fix Node.js 16 warning.
=> Upgraded to webfactory/ssh-agent@v0.9.0 to fix Node.js 16 warning

.github/workflows/build.yml
=> Updated build

slack/action.yml
Upgraded runtime of Slack action from node16 to node20
=> Upgraded runtime of Slack action from node16 to node20

.github/dependencies.yml, setup/README.md, setup/action.yml
Added cron for dependencies update.
=> Added cron for dependencies update

setup/README.md, setup/action.yml
Added Java and Android support.
=> Added Java and Android support

.github/dependabot.yml
Switched dependabot to weekly.
=> Switched dependabot to weekly

soup/action.yml
=> Switched to Ruby 3.3.3

docker/README.md, docker/action.yml, readme.md
Added action to publish images to DockerHub.
=> Added action to publish images to DockerHub

soup/action.yml
=> Update to Ruby 3.3.4

soup/action.yml
=> Updated Ruby

linters/flake8/action.yml
Fix attempt for Flake8 linter failing of `error: externally-managed-environment`.
See https://github.com/Cloud-Officer/aws/actions/runs/11333211851/job/31516904833?pr=433
This fixed the problem in our User Data script.
=> Fix attempt for Flake8 linter failing

soup/action.yml
=> Updated to Ruby 3.3.6

slack/index.js
=> Added debug to slack action

docker/action.yml, linters/rubocop/action.yml, setup/action.yml
Updated actions to latest version.
=> Updated actions to latest version

slack/index.js
=> Various fixes for eslint

.github/dependabot.yml
Force CVE only for Dependabot.
=> Force CVE only for Dependabot

soup/action.yml
=> Updated Ruby to 3.4.3

.idea/inspectionProfiles/Project_Default.xml, readme.md, soup/action.yml
=> Updated to Ruby 3.4.4

soup/action.yml
=> Updated Ruby to 3.4.5.

.markdownlint.yml
=> Updated markdownlint config

linters/markdownlint/action.yml
=> Upgraded to markdownlint v2
